travis:
  secure:
    BINSTAR_TOKEN: a1CenYNuv3L2Kfg+F1nGfMDlxH/RyOAlhf0H2s8DSi7+GB9I3QM/EKuqrvTuWINmEfSMIRR2KXhjmVDskOUwkojIxYwqwigC3P2uJEJ63Ls6X7d1EH4hWUxP/J+Ycsqkm9AAqQ4HlDSJV0C6kS2HGslmpQMvRFKqqkuD+f//+jxwFUjfIHnk+4byaSpPUjc8BOnJxMQ4XWRMzfXOqBgeL1E57KHp43AqfFLaXv/qiXljTCe0xGZRNI643nTiYahsIvPbf3FOq5iVzGe8HxN6PC+gt+OkOLZx6auihsHK2prStDkexgaywG+2/t7pTnK69pVkPpY6oG0eERpwo8k0X+Kfjcc8vDjQMLcOF7eCQ1mI3aYNC5fDKig/jnlne+iBI2xneyW4dZ3YKWA2q6LJuaHnbDaMOxgDXMZ3x/ZdUr+4F5HixdlKLNTL8Sds+pRKHeGe//FUfjhOG18H/v8BRuv7XUvWvNYjwqrCvd3QjLcJ5K41uPjdGmMFPeYp5yhbfPJq3Y5j9ACf+Ia3eMgJIFtWoFDCH+fAon2t0JORpvMnugckBR+akKqb/LS49eaMl6roZcBrE2fdij7Fq6G+0rFklb/KTiFwPYNtOmc9hSsnZYzfitq/vTae8LNdr3nmkqpmWWIlhlWtYnolt5c+LfuRnPp0BTRD8jeqFR8rmp4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
