travis:
  secure:
    BINSTAR_TOKEN: LjjrJLu9/nycgN1ER2MpWdUoLrO5swk/FMaiaBtEYunY67w2itz6PYJMCB9PCIvC044b4YPgrOji91OBkSWRBp4EUu+moO0J7xkGQ9d0v/j9tiyb2WGT12H/GLKwd3w2tRFiQWec509hnRlV6pbjxt0obce5/ahaJ0VYQ8z//w6s85TJ3u0NIaA5+yL5l7gnCPRWrzLnH+EJ3uUuZRp3yQrRiLQVeCSRxmF5CBXaGT8SbMOAVFP5rbKG91JC1QGfv/Oq38yEXZIB0f7K/z33v3JMd9n4sQjIJssObsaxOjoTOU87C00xJnbh10XZd+jc+8XQKAo3qrbOM8Y7v42sQtbXsrJvc/buWQ4QFKx8SQKsllgtD+hXlqfdpKCzsSueApKiBFxGZluBFH0dMWEX8SBAcdLflOk0ppqA1EkenWsQ/Zv4QWluF+GNuwjw1ILO4C+m3zW3hppX8avktBfVcRrTXi77bdbd785/ZDJzj+n8Z3pR07YkAp/NEavX4xrYC+oSWQ32+1x/n6BNlenolGHu7YpieDBw0VhOGfJFk3smIVwec/bBNqDPi5zBDNVb86sl+oj494/ZotWrF79jw3mqjuyfZt7juBI3gruLGZI1+/F01/ImvHQ6hroWpHjCVk0KUs11VQ8cCG8WbvZL9LXspo73Z7SATcmgeFMcdP4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
